Repository kko-okk/kko_okk, pull requests merged in 2022-06, with the labels that each got.

#17 [#16] ParentWishView, ChildWishView, ContractView, ButtonForContract …
  kko_okk.xcodeproj/project.xcworkspace/xcuserdata/kimraymond.xcuserdatad/UserInterfaceState.xcuserstate
  kko_okk/Views/BoardViews/TodoTab/ButtonForContract.swift
  kko_okk/Views/BoardViews/TodoTab/ChildWishView.swift
  kko_okk/Views/BoardViews/TodoTab/ContractView.swift
  kko_okk/Views/BoardViews/TodoTab/ParentWishView.swift
Labels: enhancement

#18 BE 구조를 다 잡았습니다.
  kko_okk.xcodeproj/project.pbxproj
  kko_okk.xcodeproj/project.xcworkspace/xcuserdata/parkgeunil.xcuserdatad/UserInterfaceState.xcuserstate
  kko_okk.xcodeproj/xcuserdata/parkgeunil.xcuserdatad/xcschemes/xcschememanagement.plist
  kko_okk/Models/TipModel.swift
  kko_okk/Persistence.swift
  kko_okk/Views/BoardViews/TodoBoardView.swift
  kko_okk/Views/BoardViews/TodoTab/ChildWishView.swift
  kko_okk/Views/BoardViews/TodoTab/ParentWishView.swift
  kko_okk/kko_okk.xcdatamodeld/kko_okk.xcdatamodel/contents
  kko_okk/kko_okkApp.swift
Labels: BackEnd

#28 CoreData의 FetchRequest를 수정하여 Filtered List를 받아올 수 있게 했습니다.
  kko_okk.xcodeproj/project.pbxproj
  kko_okk.xcodeproj/project.xcworkspace/xcuserdata/parkgeunil.xcuserdatad/UserInterfaceState.xcuserstate
  kko_okk/Models/Promise+CoreDataClass.swift
  kko_okk/Models/Promise+CoreDataProperties.swift
  kko_okk/Views/BoardViews/TodoTab/ChildWishView.swift
  kko_okk/Views/BoardViews/TodoTab/ContractView.swift
  kko_okk/Views/BoardViews/TodoTab/FilteredList.swift
  kko_okk/Views/BoardViews/TodoTab/ParentWishView.swift
  kko_okk/kko_okk.xcdatamodeld/kko_okk.xcdatamodel/contents
Labels: enhancement, BackEnd

#30 closes #24 BoardViews/TodoTab/AddPromisePopover
  kko_okk.xcodeproj/project.pbxproj
  kko_okk/Views/BoardViews/TodoTab/AddPromisePopover.swift
Labels: enhancement

#33 Feat[#31] 약속 만드는 팝오버(AddPromisePopover.swift)를 입력값에 따라 부모, 아이용으로 바뀌도록 수정할게요.
  kko_okk.xcodeproj/project.pbxproj
  kko_okk/Models/Subject.swift
  kko_okk/Views/BoardViews/TodoTab/AddPromisePopover.swift
  kko_okk/Views/BoardViews/TodoTab/ChildWishView.swift
  kko_okk/Views/BoardViews/TodoTab/EditPromisePopover.swift
  kko_okk/Views/BoardViews/TodoTab/FilteredList.swift
  kko_okk/Views/BoardViews/TodoTab/ParentWishView.swift
Labels: enhancement

#35 Fix[#34] 파일명의 수정과 확인이 파일을 못 찾는 이슈를 해결 했습니다.
  kko_okk.xcodeproj/project.pbxproj
  kko_okk/Views/HeaderView.swift
  kko_okk/Views/HeaderViews/RuyhaTestView.swift
Labels: bug

#40 Feat[#29] 가로모드 고정, 아이패드에서만 빌드가능 설정
  kko_okk.xcodeproj/project.pbxproj
Labels: enhancement

#43 Feat[#38] 약속 수정하는 기능 추가
  kko_okk.xcodeproj/project.pbxproj
  kko_okk/Views/BoardViews/TodoTab/AddPromisePopover.swift
  kko_okk/Views/BoardViews/TodoTab/EditPromisePopover.swift
  kko_okk/Views/BoardViews/TodoTab/FilteredList.swift
  kko_okk/Views/BoardViews/TodoTab/PromiseCell.swift
Labels: enhancement

#42 약속 버튼 기본 UI 작성 완료
  kko_okk/Views/BoardViews/TodoTab/ButtonForContract.swift
Labels: enhancement

#54 TodoBoardView에서 약속 버튼 추가되는 회색 영역에 코너 라운드 추가
  kko_okk/ContentView.swift
  kko_okk/Resources/Assets.xcassets/kkookkGray1.colorset/Contents.json
  kko_okk/Resources/Assets.xcassets/kkookkGray2.colorset/Contents.json
  kko_okk/Resources/Assets.xcassets/kkookkGray3.colorset/Contents.json
  kko_okk/Resources/Assets.xcassets/kkookkGray4.colorset/Contents.json
  kko_okk/Resources/KkookkFonts/AppleSDGothicNeoB.ttf
  kko_okk/Resources/KkookkFonts/AppleSDGothicNeoEB.ttf
  kko_okk/Resources/KkookkFonts/AppleSDGothicNeoH.ttf
  kko_okk/Resources/KkookkFonts/AppleSDGothicNeoL.ttf
  kko_okk/Resources/KkookkFonts/AppleSDGothicNeoM.ttf
  kko_okk/Resources/KkookkFonts/AppleSDGothicNeoR.ttf
  kko_okk/Resources/KkookkFonts/AppleSDGothicNeoSB.ttf
  kko_okk/Resources/KkookkFonts/AppleSDGothicNeoT.ttf
  kko_okk/Resources/KkookkFonts/AppleSDGothicNeoUL.ttf
  kko_okk/Views/BoardViews/TodoBoardView.swift
  kko_okk/Views/BoardViews/TodoTab/ButtonForContract.swift
  kko_okk/Views/BoardViews/TodoTab/FilteredList.swift
  kko_okk/Views/BoardViews/TodoTab/ParentWishView.swift
  kko_okk/Views/BoardViews/TodoTab/PromiseCell.swift
Labels: enhancement

#53 Header view/rolling banner view
  kko_okk.xcodeproj/project.pbxproj
  kko_okk/Views/HeaderView.swift
  kko_okk/Views/HeaderViews/BannerViews.swift
  kko_okk/Views/HeaderViews/RollingBannerView.swift
Labels: enhancement

#56 HOTFIX: 버튼 눌렀을 때 버튼으로 추가 기능 핫픽스
  kko_okk/Views/BoardViews/TodoBoardView.swift
  kko_okk/Views/BoardViews/TodoTab/ButtonForContract.swift
  kko_okk/Views/BoardViews/TodoTab/ChildWishView.swift
  kko_okk/Views/BoardViews/TodoTab/ContractView.swift
  kko_okk/Views/BoardViews/TodoTab/FilteredList.swift
  kko_okk/Views/BoardViews/TodoTab/ParentWishView.swift
Labels: bug

#57 Feat[#29]: ReportBoard 안에 있는 DailyReportView 구현
  kko_okk.xcodeproj/project.pbxproj
  kko_okk/Extensions/Font.swift
  kko_okk/Models/MockupData/DailyReportData.swift
  kko_okk/Views/BoardViews/DailyReportView.swift
Labels: enhancement

#66 부모/아이 여부에 따라 다른 색상의 버튼을 각각의 뷰에 추가하는 코드 작성
  .idea/.gitignore
  .idea/kko_okk.iml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/xcode.xml
  kko_okk.xcodeproj/project.pbxproj
  kko_okk.xcodeproj/project.xcworkspace/xcuserdata/kimraymond.xcuserdatad/UserInterfaceState.xcuserstate
  kko_okk.xcodeproj/project.xcworkspace/xcuserdata/parkgeunil.xcuserdatad/UserInterfaceState.xcuserstate
Labels: bug, enhancement

#67 Feat[#50, #60] 베이스 브랜치를 main에서 Develop으로 변경하는 과정에서 닫힌 PR 두 개를 다시 PR.
  kko_okk.xcodeproj/project.pbxproj
  kko_okk/Extensions/Font.swift
  kko_okk/Models/MockupData/DailyReportData.swift
  kko_okk/Models/Promise+CoreDataProperties.swift
  kko_okk/Models/Subject.swift
  kko_okk/Views/BoardViews/DailyReportView.swift
  kko_okk/Views/BoardViews/TodoTab/AddPromisePopover.swift
  kko_okk/Views/BoardViews/TodoTab/EditPromisePopover.swift
  kko_okk/Views/BoardViews/TodoTab/PromiseCell.swift
  kko_okk/kko_okk.xcdatamodeld/kko_okk.xcdatamodel/contents
Labels: enhancement

#78 Fix[#75]: Popover에서 요일 버튼 순서가 랜덤으로 등장하는 문제 해결
  kko_okk.xcodeproj/project.pbxproj
  kko_okk/Views/BoardViews/TodoTab/AddPromisePopover.swift
  kko_okk/Views/BoardViews/TodoTab/ChildWishView.swift
  kko_okk/Views/BoardViews/TodoTab/EditPromisePopover.swift
  kko_okk/Views/BoardViews/TodoTab/ParentWishView.swift
  kko_okk/Views/BoardViews/TodoTab/PromisePopoverElements/EditContentsOfPromiseView.swift
  kko_okk/Views/BoardViews/TodoTab/PromisePopoverElements/EditRepeatingDaysOfPromiseView.swift
  kko_okk/Views/BoardViews/TodoTab/PromisePopoverElements/PopoverViewAssets.swift
Labels: bug

#79 Feat[#68] HIFI에 맞게 팝오버 UI 개선
  kko_okk.xcodeproj/project.pbxproj
  kko_okk/Extensions/Font.swift
  kko_okk/Views/BoardViews/TodoTab/AddPromisePopover.swift
  kko_okk/Views/BoardViews/TodoTab/EditPromisePopover.swift
  kko_okk/Views/BoardViews/TodoTab/PromisePopoverElements/EditContentsOfPromiseView.swift
  kko_okk/Views/BoardViews/TodoTab/PromisePopoverElements/EditRepeatingDaysOfPromiseView.swift
  kko_okk/Views/BoardViews/TodoTab/PromisePopoverElements/PopoverAssets.swift
  kko_okk/Views/BoardViews/TodoTab/PromisePopoverElements/PopoverViewAssets.swift
Labels: enhancement

#82 [#58]: ReportBoard 안에 있는 WeeklyReportView 를 구현했습니다.
  kko_okk.xcodeproj/project.pbxproj
  kko_okk/Extensions/Font.swift
  kko_okk/Models/Date.swift
  kko_okk/Models/MockupData/WeeklyReportData.swift
  kko_okk/Views/BoardViews/ReportBoardView.swift
  kko_okk/Views/BoardViews/ReportTab/WeeklyReportView.swift
Labels: enhancement

#85 HOTFIX[#84] 컴파일 에러 해결
  kko_okk/Views/BoardViews/TodoTab/AddPromisePopover.swift
  kko_okk/Views/BoardViews/TodoTab/EditPromisePopover.swift
Labels: bug

#94 On boarding view 중간 정산입니다.
  kko_okk.xcodeproj/project.pbxproj
  kko_okk.xcodeproj/project.xcworkspace/xcuserdata/parkgeunil.xcuserdatad/UserInterfaceState.xcuserstate
  kko_okk/Extensions/Color.swift
  kko_okk/Extensions/Size.swift
  kko_okk/Models/Promise+CoreDataProperties.swift
  kko_okk/Models/PromiseModel.swift
  kko_okk/Resources/Assets.xcassets/gray6.colorset/Contents.json
  kko_okk/Resources/Assets.xcassets/kkookkYellow.colorset/Contents.json
  kko_okk/Resources/Assets.xcassets/onBoarding.imageset/Contents.json
  kko_okk/Resources/Assets.xcassets/onBoarding.imageset/onBoarding.png
  kko_okk/Resources/Assets.xcassets/onBoardingGreen.colorset/Contents.json
  kko_okk/Resources/Assets.xcassets/onBoardingPurple.colorset/Contents.json
  kko_okk/Resources/Assets.xcassets/onBoardingYellow.colorset/Contents.json
  kko_okk/Views/MainView.swift
  kko_okk/Views/OnBoardingTabView.swift
  kko_okk/Views/OnBordingViews/ButtonForOnboarding.swift
  kko_okk/Views/OnBordingViews/OnBoardingFirst.swift
  kko_okk/Views/OnBordingViews/OnBoardingForth.swift
  kko_okk/Views/OnBordingViews/OnBoardingSecond.swift
  kko_okk/Views/OnBordingViews/OnBoardingThird.swift
  kko_okk/kko_okkApp.swift
Labels: enhancement

#90 Feat[#87] 약속 셀의 "⋮" 버튼에 수정하기 팝오버 연결, [ #88] 합의되지 않은 약속을 삭제하는 기능 추가
  kko_okk/Views/BoardViews/TodoTab/ButtonForContract.swift
Labels: enhancement

#96 Fix[#91]: 약속 내용 수정 시 바로 ButtonForContract에 반영되도록 변경; Feat[#93]: 새로운 약속이 맨 아래에 추가되도록 변경
  kko_okk.xcodeproj/project.pbxproj
  kko_okk/Views/BoardViews/TodoTab/ButtonForContract.swift
  kko_okk/Views/BoardViews/TodoTab/ChildWishView.swift
  kko_okk/Views/BoardViews/TodoTab/FilteredList.swift
  kko_okk/Views/BoardViews/TodoTab/ParentWishView.swift
  kko_okk/Views/BoardViews/TodoTab/PromiseCell.swift
Labels: enhancement

#104 OnBoarding이 드래그로만 이동하는 것을 수정하고 사용하지 않게된 파일들을 삭제했습니다.
  kko_okk.xcodeproj/project.pbxproj
  kko_okk.xcodeproj/project.xcworkspace/xcuserdata/parkgeunil.xcuserdatad/UserInterfaceState.xcuserstate
  kko_okk/Models/PromiseModel.swift
  kko_okk/Views/MainView.swift
  kko_okk/Views/OnBoardingTabView.swift
  kko_okk/Views/OnBordingViews/ButtonForOnboarding.swift
  kko_okk/Views/OnBordingViews/OnBoardingButton.swift
  kko_okk/Views/OnBordingViews/OnBoardingFirst.swift
  kko_okk/Views/OnBordingViews/OnBoardingForth.swift
  kko_okk/Views/OnBordingViews/OnBoardingSecond.swift
  kko_okk/Views/OnBordingViews/OnBoardingThird.swift
  kko_okk/kko_okkApp.swift
Labels: bug

#106 Fix[#80, #81], Feat[#98]: 팝오버와 관련된 자잘한 버그를 해결하고, 레이아웃을 개선했습니다.
  kko_okk.xcodeproj/project.pbxproj
  kko_okk/Views/BoardViews/TodoTab/AddPromisePopover.swift
  kko_okk/Views/BoardViews/TodoTab/ButtonForContract.swift
  kko_okk/Views/BoardViews/TodoTab/ChildWishView.swift
  kko_okk/Views/BoardViews/TodoTab/EditPromisePopover.swift
  kko_okk/Views/BoardViews/TodoTab/ParentWishView.swift
  kko_okk/Views/BoardViews/TodoTab/PromisePopoverElements/EditContentsOfPromiseView.swift
  kko_okk/Views/BoardViews/TodoTab/PromisePopoverElements/PopoverAssets.swift
Labels: bug, enhancement

#115 Feat[#111] : promised 약속들의 확인 버튼 구현과 및 애니메이션을 추가했습니다.
  kko_okk.xcodeproj/project.pbxproj
  kko_okk/Views/BoardViews/TodoTab/ButtonForContract.swift
Labels: enhancement

#129 Feat[#121] 완료된 약속을 하단에 배치하기; Fix[#125] 약속 합의, 약속 완료 여부가 CoreData에 저장되지 않는 문제 해결
  kko_okk/Views/BoardViews/TodoTab/ButtonForContract.swift
  kko_okk/Views/BoardViews/TodoTab/ContractView.swift
  kko_okk/Views/BoardViews/TodoTab/FilteredList.swift
Labels: bug, enhancement

#124 Feat[#119] 체크마크 크기, 위치, 두께 조정; Feat[#103] 앱 라이트 모드 고정
  kko-okk-Info.plist
  kko_okk/Views/BoardViews/TodoTab/ButtonForContract.swift
Labels: enhancement

#140 레이먼드가 작업한 내용이 빌드 오류 이전으로 Revert하는 과정에서 같이 돌아가서 복구했습니다.
  kko_okk/Models/TipModel.swift
  kko_okk/Views/BoardViews/TodoTab/ButtonForContract.swift
  kko_okk/Views/HeaderViews/TitleView.swift
Labels: bug

#134 Feat[#116] Report board view 배치
  kko_okk.xcodeproj/project.pbxproj
  kko_okk/Extensions/Font.swift
  kko_okk/Views/BoardViews/ReportBoardView.swift
  kko_okk/Views/BoardViews/ReportTab/DailyReportView/DailyReportView.swift
  kko_okk/Views/BoardViews/ReportTab/WeeklyReportView/BarGraph/BarGraph.swift
  kko_okk/Views/BoardViews/ReportTab/WeeklyReportView/WeeklyReportView.swift
  kko_okk/Views/BoardViews/ReportTab/checkPromiseView/checkPromiseView.swift
Labels: enhancement

#146 Fix : Button Color를 수정하고 count를 쓰면 셀의 개수가 반환되는 것을 확인했습니다.
  kko_okk.xcodeproj/project.pbxproj
  kko_okk.xcodeproj/project.xcworkspace/xcuserdata/parkgeunil.xcuserdatad/UserInterfaceState.xcuserstate
  kko_okk/Views/BoardViews/TodoTab/ButtonForContract.swift
  kko_okk/Views/BoardViews/TodoTab/FilteredList.swift
  kko_okk/Views/OnBoardingTabView.swift
  kko_okk/Views/OnBordingViews/OnBoardingFirst.swift
  kko_okk/Views/OnBordingViews/OnBoardingForth.swift
  kko_okk/Views/OnBordingViews/OnBoardingSecond.swift
  kko_okk/Views/OnBordingViews/OnBoardingThird.swift
  kko_okk/kko_okkApp.swift
Labels: bug, enhancement

#155 Fix : HeaderView 팁 부분 롤링 베너로 이주 하겠습니다. #135
  kko_okk/Views/HeaderView.swift
  kko_okk/Views/HeaderViews/BannerViews.swift
  kko_okk/Views/HeaderViews/RollingBannerView.swift
  kko_okk/Views/HeaderViews/TitleView.swift
Labels: wontfix

#163 Fix[#161] 충돌 설정 해결
  kko_okk/Models/Resources/Assets.xcassets/Ruyha_KKooKK.imageset/Ruyha_KKooKK-1.png
  kko_okk/Models/Resources/Assets.xcassets/Ruyha_KKooKK.imageset/Ruyha_KKooKK-2.png
  kko_okk/Models/Resources/Assets.xcassets/Ruyha_KKooKK.imageset/Ruyha_KKooKK.png
  kko_okk/Views/HeaderViews/RollingBannerView.swift
  kko_okk/Views/HeaderViews/TitleView.swift
Labels: wontfix

#152 Fix: 온보딩 페이지 3, 4번에서 비활성화된 버튼이 눌리는 문제 해결
  kko_okk/Views/OnBordingViews/OnBoardingForth.swift
  kko_okk/Views/OnBordingViews/OnBoardingThird.swift
Labels: bug

#173 + 버튼에 손가락 끝 모양 도형 추가
  .idea/.gitignore
  .idea/kko_okk.iml
  .idea/mc2.iml
  .idea/modules.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_6_18_22,_9_11_AM_[Changes]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_6_18_22__9_11_AM__Changes_.xml
  .idea/workspace.xml
  .idea/xcode.xml
  README.md
  kko_okk.xcodeproj/project.pbxproj
  kko_okk/Models/Resources/Assets.xcassets/childFingerprint.imageset/Contents.json
  kko_okk/Models/Resources/Assets.xcassets/childFingerprint.imageset/childFingerprint.png
  kko_okk/Models/Resources/Assets.xcassets/parentFingerprint.imageset/Contents.json
  kko_okk/Models/Resources/Assets.xcassets/parentFingerprint.imageset/parentFingerprint.png
  kko_okk/Views/BoardViews/TodoTab/ChildWishView.swift
  kko_okk/Views/BoardViews/TodoTab/ParentWishView.swift
Labels: enhancement

#175 HOTFIX: [#174] 변경된 파일 구조를 고려하여 손가락 끝 모양 이미지를 추가했습니다.
  kko_okk/Views/BoardViews/TodoTab/FilteredList.swift
Labels: bug, enhancement, Refactoring

#179 Heander view/rolling banner view
  kko_okk/Models/Resources/Assets.xcassets/OneHand.imageset/Contents.json
  kko_okk/Models/Resources/Assets.xcassets/OneHand.imageset/OneHand-1.png
  kko_okk/Models/Resources/Assets.xcassets/OneHand.imageset/OneHand-2.png
  kko_okk/Models/Resources/Assets.xcassets/OneHand.imageset/OneHand.png
  kko_okk/Models/TipModel.swift
  kko_okk/Views/BoardViews/ReportTab/checkPromiseView/checkPromiseView.swift
  kko_okk/Views/HeaderView.swift
  kko_okk/Views/HeaderViews/BannerViews.swift
  kko_okk/Views/HeaderViews/HeaderViewConst.swift
  kko_okk/Views/HeaderViews/RollingBannerView.swift
  kko_okk/Views/HeaderViews/TitleView.swift
  kko_okk/kko_okkApp.swift
Labels: enhancement, Refactoring

#190 Setting view
  kko-okk-Info.plist
  kko_okk.xcodeproj/project.pbxproj
  kko_okk/BugMailView.swift
  kko_okk/Models/Resources/Assets.xcassets/GitHub.imageset/Contents.json
  kko_okk/Models/Resources/Assets.xcassets/GitHub.imageset/GitHub-1.png
  kko_okk/Models/Resources/Assets.xcassets/GitHub.imageset/GitHub-Mark-120px-plus.png
  kko_okk/Models/Resources/Assets.xcassets/GitHub.imageset/GitHub-Mark-32px.png
  kko_okk/Models/Resources/Assets.xcassets/Guell.imageset/Contents.json
  kko_okk/Models/Resources/Assets.xcassets/Guell.imageset/Guell-1.png
  kko_okk/Models/Resources/Assets.xcassets/Guell.imageset/Guell-2.png
  kko_okk/Models/Resources/Assets.xcassets/Guell.imageset/Guell.png
  kko_okk/Models/Resources/Assets.xcassets/Ian.imageset/Contents.json
  kko_okk/Models/Resources/Assets.xcassets/Ian.imageset/Ian (1).png
  kko_okk/Models/Resources/Assets.xcassets/Ian.imageset/Ian (2)-1.png
  kko_okk/Models/Resources/Assets.xcassets/Ian.imageset/Ian (2).png
  kko_okk/Models/Resources/Assets.xcassets/Raymond.imageset/Contents.json
  kko_okk/Models/Resources/Assets.xcassets/Raymond.imageset/Raymond-1.png
  kko_okk/Models/Resources/Assets.xcassets/Raymond.imageset/Raymond-2.png
  kko_okk/Models/Resources/Assets.xcassets/Raymond.imageset/Raymond.png
  kko_okk/Models/Resources/Assets.xcassets/Ruyha.imageset/Contents.json
  kko_okk/Models/Resources/Assets.xcassets/Ruyha.imageset/Ruya-1.png
  kko_okk/Models/Resources/Assets.xcassets/Ruyha.imageset/Ruya-2.png
  kko_okk/Models/Resources/Assets.xcassets/Ruyha.imageset/Ruya.png
  kko_okk/Models/Resources/Assets.xcassets/SeoDam.imageset/Contents.json
  kko_okk/Models/Resources/Assets.xcassets/SeoDam.imageset/SeoDam-1.png
  kko_okk/Models/Resources/Assets.xcassets/SeoDam.imageset/SeoDam-2.png
  kko_okk/Models/Resources/Assets.xcassets/SeoDam.imageset/SeoDam.png
  kko_okk/Models/Resources/Assets.xcassets/Yeni.imageset/Contents.json
  kko_okk/Models/Resources/Assets.xcassets/Yeni.imageset/Yeni (1)-1.png
  kko_okk/Models/Resources/Assets.xcassets/Yeni.imageset/Yeni (1).png
  kko_okk/Models/Resources/Assets.xcassets/Yeni.imageset/Yeni.png
  kko_okk/Views/BoardViews/SettingView.swift
  kko_okk/Views/BoardViews/SettingViews/LicenseView.swift
  kko_okk/Views/BoardViews/SettingViews/MailView.swift
  kko_okk/Views/BoardViews/SettingViews/WebView.swift
Labels: enhancement

#191 Fix: 류하 거랑 충돌을 제거 했습니다.
  kko_okk.xcodeproj/project.pbxproj
  kko_okk.xcodeproj/project.xcworkspace/xcuserdata/parkgeunil.xcuserdatad/UserInterfaceState.xcuserstate
  kko_okk/Models/Date.swift
  kko_okk/Models/DateExtension.swift
  kko_okk/Models/MockupData/DailyReportData.swift
  kko_okk/Models/MockupData/MonthlyReportData.swift
  kko_okk/Models/MockupData/WeeklyReportData.swift
  kko_okk/Models/PickedDate.swift
  kko_okk/Models/Promise+CoreDataProperties.swift
  kko_okk/Views/BoardViews/ReportBoardView.swift
  kko_okk/Views/BoardViews/ReportTab/DailyReportView/AnimatedDailyReportView.swift
  kko_okk/Views/BoardViews/ReportTab/DailyReportView/DailyReportView.swift
  kko_okk/Views/BoardViews/ReportTab/MonthlyReportView/CustomDatePicker.swift
  kko_okk/Views/BoardViews/ReportTab/MonthlyReportView/MonthlyReportView.swift
  kko_okk/Views/BoardViews/ReportTab/WeeklyReportView/BarGraph/BarGraph.swift
  kko_okk/Views/BoardViews/ReportTab/WeeklyReportView/WeeklyReportView.swift
  kko_okk/Views/BoardViews/ReportTab/checkPromiseView/checkPromiseView.swift
  kko_okk/Views/BoardViews/TodoBoardView.swift
  kko_okk/Views/BoardViews/TodoTab/AddPromisePopover.swift
  kko_okk/Views/BoardViews/TodoTab/ChildWishView.swift
  kko_okk/Views/BoardViews/TodoTab/ContractView.swift
  kko_okk/Views/BoardViews/TodoTab/FilteredList.swift
  kko_okk/Views/BoardViews/TodoTab/ParentWishView.swift
  kko_okk/Views/HeaderView.swift
  kko_okk/Views/HeaderViews/DatePickerView.swift
  kko_okk/Views/HeaderViews/TitleView.swift
  kko_okk/Views/OnBordingViews/OnBoardingForth.swift
  kko_okk/Views/SegmentView.swift
  kko_okk/kko_okkApp.swift
Labels: bug, enhancement

#198 [#181] 시스템 컬러를 꼬옥 컬러로 변경
  kko_okk/Views/BoardViews/ReportBoardView.swift
  kko_okk/Views/BoardViews/ReportTab/DailyReportView/DailyReportView.swift
  kko_okk/Views/BoardViews/ReportTab/MonthlyReportView/CustomDatePicker.swift
  kko_okk/Views/BoardViews/ReportTab/WeeklyReportView/BarGraph/BarGraph.swift
  kko_okk/Views/BoardViews/TodoTab/AddPromisePopover.swift
  kko_okk/Views/BoardViews/TodoTab/ButtonForContract.swift
  kko_okk/Views/BoardViews/TodoTab/EditPromisePopover.swift
  kko_okk/Views/BoardViews/TodoTab/FilteredList.swift
  kko_okk/Views/BoardViews/TodoTab/PromisePopoverElements/EditContentsOfPromiseView.swift
  kko_okk/Views/OnBordingViews/OnBoardingFirst.swift
  kko_okk/Views/OnBordingViews/OnBoardingForth.swift
  kko_okk/Views/OnBordingViews/OnBoardingSecond.swift
  kko_okk/Views/OnBordingViews/OnBoardingThird.swift
Labels: enhancement

#207 Feat[#206] App store set
  kko-okk-Info.plist
  kko_okk.xcodeproj/project.pbxproj
  kko_okk/Models/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  kko_okk/Models/Resources/Assets.xcassets/AppIcon.appiconset/Icon-1024.png
  kko_okk/Models/Resources/Assets.xcassets/AppIcon.appiconset/Icon-120.png
  kko_okk/Models/Resources/Assets.xcassets/AppIcon.appiconset/Icon-121.png
  kko_okk/Models/Resources/Assets.xcassets/AppIcon.appiconset/Icon-152.png
  kko_okk/Models/Resources/Assets.xcassets/AppIcon.appiconset/Icon-167.png
  kko_okk/Models/Resources/Assets.xcassets/AppIcon.appiconset/Icon-180.png
  kko_okk/Models/Resources/Assets.xcassets/AppIcon.appiconset/Icon-20.png
  kko_okk/Models/Resources/Assets.xcassets/AppIcon.appiconset/Icon-29.png
  kko_okk/Models/Resources/Assets.xcassets/AppIcon.appiconset/Icon-40.png
  kko_okk/Models/Resources/Assets.xcassets/AppIcon.appiconset/Icon-41.png
  kko_okk/Models/Resources/Assets.xcassets/AppIcon.appiconset/Icon-42.png
  kko_okk/Models/Resources/Assets.xcassets/AppIcon.appiconset/Icon-58.png
  kko_okk/Models/Resources/Assets.xcassets/AppIcon.appiconset/Icon-59.png
  kko_okk/Models/Resources/Assets.xcassets/AppIcon.appiconset/Icon-60.png
  kko_okk/Models/Resources/Assets.xcassets/AppIcon.appiconset/Icon-76.png
  kko_okk/Models/Resources/Assets.xcassets/AppIcon.appiconset/Icon-80.png
  kko_okk/Models/Resources/Assets.xcassets/AppIcon.appiconset/Icon-81.png
  kko_okk/Models/Resources/Assets.xcassets/AppIcon.appiconset/Icon-87.png
  kko_okk/en.lproj/InfoPlist.strings
  kko_okk/ko.lproj/InfoPlist.strings
Labels: enhancement

#209 Feat[#208] Localizing 처리 완료 (영어번역필요)
  kko_okk.xcodeproj/project.pbxproj
  kko_okk/Extensions/Extensions.swift
  kko_okk/Models/Date.swift
  kko_okk/Models/MockupData/WeeklyReportData.swift
  kko_okk/Models/TipModel.swift
  kko_okk/Views/BoardViews/ReportTab/DailyReportView/DailyReportView.swift
  kko_okk/Views/BoardViews/ReportTab/MonthlyReportView/CustomDatePicker.swift
  kko_okk/Views/BoardViews/ReportTab/WeeklyReportView/WeeklyReportView.swift
  kko_okk/Views/BoardViews/ReportTab/checkPromiseView/checkPromiseView.swift
  kko_okk/Views/BoardViews/SettingView.swift
  kko_okk/Views/BoardViews/SettingViews/MailView.swift
  kko_okk/Views/BoardViews/TodoTab/AddPromisePopover.swift
  kko_okk/Views/BoardViews/TodoTab/ButtonForContract.swift
  kko_okk/Views/BoardViews/TodoTab/EditPromisePopover.swift
  kko_okk/Views/BoardViews/TodoTab/FilteredList.swift
  kko_okk/Views/BoardViews/TodoTab/PromisePopoverElements/EditContentsOfPromiseView.swift
  kko_okk/Views/BoardViews/TodoTab/PromisePopoverElements/EditRepeatingDaysOfPromiseView.swift
  kko_okk/Views/HeaderViews/BannerViews.swift
  kko_okk/Views/HeaderViews/HeaderViewConst.swift
  kko_okk/Views/HeaderViews/RollingBannerView.swift
  kko_okk/Views/HeaderViews/TitleView.swift
  kko_okk/Views/OnBordingViews/OnBoardingFirst.swift
  kko_okk/Views/OnBordingViews/OnBoardingForth.swift
  kko_okk/Views/OnBordingViews/OnBoardingSecond.swift
  kko_okk/Views/OnBordingViews/OnBoardingThird.swift
  kko_okk/Views/SegmentView.swift
  kko_okk/en.lproj/Localizable.strings
  kko_okk/ko.lproj/Localizable.strings
Labels: enhancement
