Repository kko-okk/kko_okk, pull requests merged in 2022-07, with the labels that each got.

#219 Create LICENSE
  LICENSE
Labels: documentation, enhancement, MVP

#222 Educational Tips Update
  kko_okk/Views/HeaderViews/RollingBannerView.swift
  kko_okk/en.lproj/Localizable.strings
Labels: documentation, enhancement, MVP

#229 교육 팁 20개로 추가 업데이트
  kko_okk/Models/TipModel.swift
  kko_okk/en.lproj/Localizable.strings
Labels: documentation, enhancement, MVP

#226 feat[#225] 빌드버전 수정, 팁 모델 수정, 한글팁 줄바꿈 수정
  kko_okk.xcodeproj/project.pbxproj
  kko_okk/Models/TipModel.swift
  kko_okk/Views/SegmentView.swift
  kko_okk/en.lproj/Localizable.strings
  kko_okk/ko.lproj/Localizable.strings
Labels: enhancement

#234 On board refactoring
  kko_okk/Extensions/Extensions.swift
  kko_okk/Views/BoardViews/TodoBoardView.swift
  kko_okk/Views/OnBordingViews/Buttons/OnBoardingButton.swift
  kko_okk/Views/OnBordingViews/Buttons/OnBoardingButtonsViewModifier.swift
  kko_okk/Views/OnBordingViews/Buttons/OnBoardingChildButton.swift
  kko_okk/Views/OnBordingViews/Buttons/OnBoardingContractButton.swift
  kko_okk/Views/OnBordingViews/Buttons/OnBoardingParentButton.swift
  kko_okk/Views/OnBordingViews/OnBoardingButtons/OnBoardingButton.swift
  kko_okk/Views/OnBordingViews/OnBoardingButtons/OnBoardingButtonsViewModifier.swift
  kko_okk/Views/OnBordingViews/OnBoardingButtons/OnBoardingChildButton.swift
  kko_okk/Views/OnBordingViews/OnBoardingButtons/OnBoardingContractButton.swift
  kko_okk/Views/OnBordingViews/OnBoardingButtons/OnBoardingParentButton.swift
  kko_okk/Views/OnBordingViews/OnBoardingMainView.swift
  kko_okk/Views/SegmentView.swift
Labels: Refactoring

#237 On boarding refactoring
  kko_okk/Views/BoardViews/TodoTab/AddWishPopover.swift
  kko_okk/Views/BoardViews/TodoTab/FilteredList.swift
  kko_okk/Views/MainView.swift
  kko_okk/Views/OnBordingViews/OnBoardingButtons/OnBoardingButtonsViewModifier.swift
  kko_okk/Views/OnBordingViews/OnBoardingButtons/OnBoardingChildButton.swift
  kko_okk/Views/OnBordingViews/OnBoardingButtons/OnBoardingContractButton.swift
  kko_okk/Views/OnBordingViews/OnBoardingButtons/OnBoardingParentButton.swift
  kko_okk/Views/OnBordingViews/OnBoardingFirst.swift
  kko_okk/Views/OnBordingViews/OnBoardingForth.swift
  kko_okk/Views/OnBordingViews/OnBoardingMainView.swift
  kko_okk/Views/OnBordingViews/OnBoardingSegmentView.swift
  kko_okk/Views/OnBordingViews/OnBoardingThird.swift
  kko_okk/Views/SegmentView.swift
  kko_okk/kko_okkApp.swift
Labels: Refactoring

#239 Revert: to [#225] 8b94693d4997e5aa8f8f5f5b0f743b4c057c1cb6
  kko_okk/Views/OnBordingViews/OnBoardingButtons/OnBoardingButtonsViewModifier.swift
  kko_okk/Views/OnBordingViews/OnBoardingButtons/OnBoardingChildButtonView.swift
  kko_okk/Views/OnBordingViews/OnBoardingButtons/OnBoardingContractButtonView.swift
  kko_okk/Views/OnBordingViews/OnBoardingButtons/OnBoardingParentButtonView.swift
  kko_okk/Views/OnBordingViews/OnBoardingMainView.swift
  kko_okk/Views/OnBordingViews/OnBoardingSegmentView.swift
Labels: Refactoring, MVP

#242 Date formatter
  kko_okk/Models/Date.swift
  kko_okk/Models/DateExtension.swift
  kko_okk/Views/BoardViews/ReportTab/DailyReportView/DailyReportView.swift
  kko_okk/Views/BoardViews/ReportTab/MonthlyReportView/CustomDatePicker.swift
  kko_okk/Views/BoardViews/ReportTab/WeeklyReportView/BarGraph/BarGraph.swift
  kko_okk/Views/BoardViews/ReportTab/WeeklyReportView/WeeklyReportView.swift
  kko_okk/Views/HeaderViews/HeaderViewConst.swift
Labels: bug

#241 Fix: AddPromisePopover.swift 참조 이슈 복구
  kko_okk/Views/BoardViews/TodoTab/AddPromisePopover.swift
  kko_okk/Views/BoardViews/TodoTab/FilteredList.swift
  kko_okk/Views/OnBordingViews/OnBoardingButtons/OnBoardingButtonsViewModifier.swift
  kko_okk/Views/OnBordingViews/OnBoardingSegmentView.swift
Labels: bug, Refactoring, MVP
